#!/usr/bin/env bash
# Print a Nix derivation for a claude-recall release, for babarot/nur-packages.
# Usage: nix-derivation.sh <version> <checksums.txt>
set -euo pipefail

version=$1
checksums=$2

sha() {
  local sum
  sum=$(awk -v f="$1" '$2 == f { print $1 }' "$checksums")
  if [[ -z $sum ]]; then
    echo "no checksum for $1 in $checksums" >&2
    exit 1
  fi
  echo "$sum"
}

cat <<NIX
# This file was generated by claude-recall's release workflow. DO NOT EDIT.
{
  lib,
  fetchurl,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  version = "${version}";
  base = "https://github.com/babarot/claude-recall/releases/download/\${version}";
  assets = {
    aarch64-darwin = {
      name = "claude-recall-darwin-arm64";
      sha256 = "$(sha claude-recall-darwin-arm64)";
    };
    x86_64-darwin = {
      name = "claude-recall-darwin-x86_64";
      sha256 = "$(sha claude-recall-darwin-x86_64)";
    };
    aarch64-linux = {
      name = "claude-recall-linux-arm64";
      sha256 = "$(sha claude-recall-linux-arm64)";
    };
    x86_64-linux = {
      name = "claude-recall-linux-x86_64";
      sha256 = "$(sha claude-recall-linux-x86_64)";
    };
  };
  asset = assets.\${system} or (throw "claude-recall: unsupported system \${system}");
  plugin = fetchurl {
    url = "\${base}/claude-recall-plugin.tar.gz";
    sha256 = "$(sha claude-recall-plugin.tar.gz)";
  };
in
stdenvNoCC.mkDerivation {
  pname = "claude-recall";
  inherit version;

  src = fetchurl {
    url = "\${base}/\${asset.name}";
    inherit (asset) sha256;
  };

  dontUnpack = true;
  # A static Go binary; stripping it again or patching it gains nothing
  dontFixup = true;

  # The Claude Code plugin (MCP server, SessionEnd hook, hooks module) lands
  # in share/claude-plugin/claude-recall
  installPhase = ''
    install -Dm755 \$src \$out/bin/recall
    mkdir -p \$out/share/claude-plugin/claude-recall
    tar -xzf \${plugin} -C \$out/share/claude-plugin/claude-recall
  '';

  meta = {
    description = "Archive and search coding agent sessions";
    homepage = "https://github.com/babarot/claude-recall";
    mainProgram = "recall";
    platforms = builtins.attrNames assets;
    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
  };
}
NIX
